dist: trusty
sudo: required

language: cpp
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages
      - g++
      - cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - ./tests/status_test